---
name: Create Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version:
          - "3.12"
        system:
          - ubuntu-24.04
    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1

      # - name: setup clang 17
      #   run: |
      #     wget https://apt.llvm.org/llvm.sh
      #     chmod +x ./llvm.sh
      #     sudo ./llvm.sh 17
      #     rm llvm.sh

      - run: sudo apt-get install clang-17 clang-format-17
      - run: sudo apt-get install lcov doxygen gcc-13 g++-13

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - run: pip${{matrix.python-version}} install vmklib yambs

      - run: mk test yaml
