---
name: Create Project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ${{matrix.system}}
    strategy:
      matrix:
        python-version:
          - "3.11"
        system:
          - ubuntu-latest
    env:
      PYTHON_VERSION: ${{matrix.python-version}}

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.11.1

      - run: sudo apt-get install lcov

      - name: python${{matrix.python-version}} setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - run: pip${{matrix.python-version}} install vmklib

      - run: mk test yaml
